[project]
name = "functions"
version = "0.1.0"
description = "Lambda function handlers"
dependencies = ["core"]
requires-python = "==3.11.*"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
core = { workspace = true }
